#!/bin/bash

#SBATCH --mem=98G
#SBATCH --time=10:00:00

ses_list="/home/ecdraper/scratch/ecdraper/SIMON/SIMON_BIDS/sub-032633/T2_proc/ses_list_T2_FLAIR"
core_path="/home/ecdraper/scratch/ecdraper/SIMON/SIMON_BIDS/sub-032633/T2_proc"

while read -r SES; do
	    echo "Processing session: ${SES}"
	fcm-normalize "$core_path/ses-${SES}/anat/sub-032633_ses-${SES}_run-1_FLAIR.anat/T2_biascorr_brain.nii.gz" -tm "$core_path/ses-${SES}/anat/sub-032633_ses-${SES}_run-1_FLAIR.anat/T2_biascorr_brain_mask.nii.gz" -o "$core_path/ses-${SES}/anat/sub-032633_ses-${SES}_run-1_T2w_fcm_brain.nii.gz" -v -mo t2
	echo "FCM has been run for ${SES}"
done < "$ses_list"
echo "five more subjects are done"
