#!/bin/bash

#SBATCH --mem=98G
#SBATCH --time=10:00:00

ses_list="/home/ecdraper/scratch/ecdraper/SIMON/SIMON_BIDS/sub-032633/T1_proc/ses_list"
core_path="/home/ecdraper/scratch/ecdraper/SIMON/SIMON_BIDS/sub-032633/T1_proc"

while read -r SES; do
	    echo "Processing session: ${SES}"
	fcm-normalize "$core_path/ses-${SES}/anat/sub-032633_ses-${SES}_run-1_T1w.anat/T1_biascorr_brain.nii.gz" -m "$core_path/ses-${SES}/anat/sub-032633_ses-${SES}_run-1_T1w.anat/T1_biascorr_brain_mask.nii.gz" -o "$core_path/ses-${SES}/anat/sub-032633_ses-${SES}_run-1_T1w_fcm_brain.nii.gz" -v -mo t1 -tt wm
	echo "FCM has been run for ${SES}"
done < "$ses_list"
echo "five more subjects are done"
