#!/bin/bash

#SBATCH --mem=98G
#SBATCH --time=10:00:00

module load fsl/6.0.7.7

ses_list="/home/ecdraper/scratch/ecdraper/SIMON/SIMON_BIDS/sub-032633/T2_proc/ses_list_T2_FLAIR"
core_path="/home/ecdraper/scratch/ecdraper/SIMON/SIMON_BIDS/sub-032633/T2_proc"

while read -r SES; do
	    echo "Processing session: ${SES}"

	INPUT="$core_path/ses-${SES}/anat/sub-032633_ses-${SES}_run-1_FLAIR.anat/T2_biascorr_brain.nii.gz"
	OUTPUT="$core_path/ses-${SES}/anat/sub-032633_ses-${SES}_run-1_FLAIR.anat/T2_reg_T1.nii.gz"
	REF="/home/ecdraper/scratch/ecdraper/SIMON/SIMON_BIDS/sub-032633/T1_proc/ses-${SES}/anat/sub-032633_ses-${SES}_run-1_T1w.anat/T1_biascorr_brain.nii.gz"
	OMAT="$core_path/ses-${SES}/anat/sub-032633_ses-${SES}_run-1_FLAIR.anat/T2_reg_T1.omat"

	flirt -in "$INPUT" -ref "$REF" -out "$OUTPUT" -omat "$OMAT" -dof 6

	echo "Flirt has been run for T2 to T1 on ${SES}"
done < "$ses_list"
echo "Flirt has been run, all T2 registered to T1"
