#!/bin/bash

#SBATCH --mem=2G
#SBATCH --time=1:00:00

module load fsl/6.0.7.7

core_path="/path/to/data"
sub_list="$core_path/sub_list"
OUTPUT_FILE="$core_path/T1_Results"
echo "ID,Method,WM_Volume,GM_Volume,WM_Min,WM_Max" > $OUTPUT_FILE

while read ID; do

	WM="$core_path/${ID}/T1/T1_cropped.anat/T1_fast_pve_2.nii.gz"
	GM="$core_path/${ID}/T1/T1_cropped.anat/T1_fast_pve_1.nii.gz"
	B="$core_path/${ID}/T1/T1_cropped.anat/T1_biascorr_brain"
	FCM="$core_path/${ID}/T1/T1_fcm_brain.nii.gz"
	WM_FCM="$core_path/${ID}/T1/T1_fcm_brain_pve_2.nii.gz"
	GM_FCM="$core_path/${ID}/T1/T1_fcm_brain_pve_1.nii.gz"
	KDE="$core_path/${ID}/T1/T1_kde_brain.nii.gz"
	WM_KDE="$core_path/${ID}/T1/T1_kde_brain_pve_2.nii.gz"
 	GM_KDE="$core_path/${ID}/T1/T1_kde_brain_pve_1.nii.gz"
	WS="$core_path/${ID}/T1/T1_ws_brain.nii.gz"
	WM_WS="$core_path/${ID}/T1/T1_ws_brain_pve_2.nii.gz"
	GM_WS="$core_path/${ID}/T1/T1_ws_brain_pve_1.nii.gz"
	ZS="$core_path/${ID}/T1/T1_zs_brain.nii.gz"
	WM_ZS="$core_path/${ID}/T1/T1_zs_brain_pve_2.nii.gz"
	GM_ZS="$core_path/${ID}/T1/T1_zs_brain_pve_1.nii.gz"

	echo "${ID},UC,$(fslstats ${WM} -V | awk '{print $2}'), $(fslstats ${GM} -V |  awk '{print $2}'), $(fslstats ${B} -k ${WM} -r)" >> $OUTPUT_FILE
	echo "${ID},FCM,$(fslstats ${WM_FCM} -V | awk '{print $2}'), $(fslstats ${GM_FCM} -V |  awk '{print $2}'), $(fslstats ${FCM} -k ${WM_FCM} -r)" >> $OUTPUT_FILE
	echo "${ID},KDE,$(fslstats ${WM_KDE} -V | awk '{print $2}'), $(fslstats ${GM_KDE} -V |  awk '{print $2}'), $(fslstats ${KDE} -k ${WM_KDE} -r)" >> $OUTPUT_FILE
	echo "${ID},WS,$(fslstats ${WM_WS} -V | awk '{print $2}'), $(fslstats ${GM_WS} -V |  awk '{print $2}'), $(fslstats ${WS} -k ${WM_WS} -r)" >> $OUTPUT_FILE
	echo "${ID},ZS,$(fslstats ${WM_ZS} -V | awk '{print $2}'), $(fslstats ${GM_ZS} -V |  awk '{print $2}'), $(fslstats ${ZS} -k ${WM_ZS} -r)" >> $OUTPUT_FILE

done < "$sub_list"

echo "White matter volume, grey matter volume, white matter min intensity, and white matter max intensity saved to $OUTPUT_FILE"
